name: CIConfirmation
main: net.xornick.ciconfirm.CIConfirmation
version: 1.0.0
author: XorNick
commands:
  clearinventory:
    description: Clears inventory with a confirmation check.
    aliases: [ci]